# Generated by Django 4.2.4 on 2023-08-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
