# Generated by Django 4.2.4 on 2023-08-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=0, editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
